# Generated by Django 2.0.5 on 2018-05-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180524_0922'),
        ('articles', '0003_auto_20171112_0905'),
    ]

    operations = [
    ]
